eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9400/eureka/
  instance: 
   hostname: ${spring.cloud.client.ipAddress}
server:
  port: 9500
spring:
  cloud:
    config:
      server:
        git:
          uri: http://192.168.1.51:10002/TestGroup/configfiles
          searchPaths: config
          username: yaoyinbing
          password: Init1234!
      label: master
  application:
    name: platform-config-server
  rabbitmq:
    host: 192.168.1.121
    port: 5672
    username: rabbitadmin
    password: 123456
management:
  security:
    enabled: false